-- Seed: 200+ marcas de ejemplo para el portafolio de ReClub
-- Ejecutar en Supabase SQL Editor para poblar la tabla

insert into portfolio_brands (name, website_url, sort_order) values
-- Retail & Moda
('Falabella', 'https://falabella.com', 1),
('Ripley', 'https://ripley.cl', 2),
('Paris', 'https://paris.cl', 3),
('H&M', 'https://hm.com', 4),
('Zara', 'https://zara.com', 5),
('Nike', 'https://nike.com', 6),
('Adidas', 'https://adidas.com', 7),
('Puma', 'https://puma.com', 8),
('New Balance', 'https://newbalance.com', 9),
('Under Armour', 'https://underarmour.com', 10),
('Levi''s', 'https://levis.com', 11),
('Tommy Hilfiger', 'https://tommy.com', 12),
('Calvin Klein', 'https://calvinklein.com', 13),
('Lacoste', 'https://lacoste.com', 14),
('Converse', 'https://converse.com', 15),

-- Tecnología
('Samsung', 'https://samsung.com', 16),
('Apple', 'https://apple.com', 17),
('Huawei', 'https://huawei.com', 18),
('Xiaomi', 'https://mi.com', 19),
('LG', 'https://lg.com', 20),
('Sony', 'https://sony.com', 21),
('HP', 'https://hp.com', 22),
('Dell', 'https://dell.com', 23),
('Lenovo', 'https://lenovo.com', 24),
('Asus', 'https://asus.com', 25),
('Microsoft', 'https://microsoft.com', 26),
('Google', 'https://google.com', 27),
('Intel', 'https://intel.com', 28),
('AMD', 'https://amd.com', 29),
('Logitech', 'https://logitech.com', 30),

-- Alimentos & Bebidas
('Nestlé', 'https://nestle.com', 31),
('Coca-Cola', 'https://coca-cola.com', 32),
('Pepsi', 'https://pepsi.com', 33),
('Unilever', 'https://unilever.com', 34),
('Carozzi', 'https://carozzi.cl', 35),
('Lider', 'https://lider.cl', 36),
('Jumbo', 'https://jumbo.cl', 37),
('Unimarc', 'https://unimarc.cl', 38),
('CCU', 'https://ccu.cl', 39),
('Ambev', 'https://ambev.com', 40),
('Corona', 'https://corona.com', 41),
('Heineken', 'https://heineken.com', 42),
('Cristal', 'https://cerveceriacristal.cl', 43),
('Escudo', '', 44),
('Quilmes', 'https://quilmes.com.ar', 45),
('Watt''s', 'https://watts.cl', 46),
('Soprole', 'https://soprole.cl', 47),
('Colun', 'https://colun.cl', 48),
('Emmi', '', 49),
('Del Monte', 'https://delmonte.com', 50),

-- Automotriz
('Toyota', 'https://toyota.com', 51),
('Hyundai', 'https://hyundai.com', 52),
('Kia', 'https://kia.com', 53),
('Chevrolet', 'https://chevrolet.com', 54),
('Ford', 'https://ford.com', 55),
('Nissan', 'https://nissan.com', 56),
('Honda', 'https://honda.com', 57),
('Volkswagen', 'https://vw.com', 58),
('BMW', 'https://bmw.com', 59),
('Mercedes-Benz', 'https://mercedes-benz.com', 60),
('Suzuki', 'https://suzuki.com', 61),
('Mitsubishi', 'https://mitsubishi.com', 62),
('Peugeot', 'https://peugeot.com', 63),
('Renault', 'https://renault.com', 64),
('Jeep', 'https://jeep.com', 65),

-- Banca & Finanzas
('Banco de Chile', 'https://bancochile.cl', 66),
('BCI', 'https://bci.cl', 67),
('Santander', 'https://santander.cl', 68),
('Itaú', 'https://itau.cl', 69),
('BBVA', 'https://bbva.cl', 70),
('Scotiabank', 'https://scotiabank.cl', 71),
('Security', 'https://bancosecurity.cl', 72),
('Consorcio', 'https://consorcio.cl', 73),
('CMR Falabella', 'https://cmrfalabella.cl', 74),
('Coopeuch', 'https://coopeuch.cl', 75),

-- Telecomunicaciones
('Entel', 'https://entel.cl', 76),
('Claro', 'https://clarochile.cl', 77),
('Movistar', 'https://movistar.cl', 78),
('WOM', 'https://wom.cl', 79),
('VTR', 'https://vtr.com', 80),
('GTD', 'https://gtd.cl', 81),
('Tigo', 'https://tigo.cl', 82),

-- Salud & Farmacias
('Cruz Verde', 'https://cruzverde.cl', 83),
('Ahumada', 'https://farmaciasahumada.cl', 84),
('Salcobrand', 'https://salcobrand.cl', 85),
('Bupa', 'https://bupa.cl', 86),
('Banmédica', 'https://banmedica.cl', 87),
('Clínica Alemana', 'https://clinicaalemana.cl', 88),
('UC Christus', 'https://redclinicauc.cl', 89),
('Megasalud', 'https://megasalud.cl', 90),
('Nueva Masvida', 'https://nuevamasvida.cl', 91),
('Colmena', 'https://colmena.cl', 92),

-- Energía & Utilities
('Copec', 'https://copec.cl', 93),
('Shell', 'https://shell.cl', 94),
('Enel', 'https://enel.cl', 95),
('CGE', 'https://cge.cl', 96),
('Metrogas', 'https://metrogas.cl', 97),
('Aguas Andinas', 'https://aguasandinas.cl', 98),

-- Inmobiliaria & Construcción
('Inmobiliaria Paz', 'https://paz.cl', 99),
('Besalco', 'https://besalco.cl', 100),
('Socovesa', 'https://socovesa.cl', 101),
('Moller & Pérez-Cotapos', 'https://moller.cl', 102),
('Echeverría Izquierdo', 'https://ei.cl', 103),
('SalfaCorp', 'https://salfa.cl', 104),
('Constructora Bravo', '', 105),
('Siena Inmobiliaria', 'https://siena.cl', 106),
('Aconcagua', '', 107),
('Ralei', 'https://ralei.cl', 108),

-- Restaurantes & Food Service
('McDonald''s', 'https://mcdonalds.cl', 109),
('Burger King', 'https://burgerking.cl', 110),
('KFC', 'https://kfc.cl', 111),
('Subway', 'https://subway.cl', 112),
('Domino''s', 'https://dominos.cl', 113),
('Pizza Hut', 'https://pizzahut.cl', 114),
('Telepizza', 'https://telepizza.cl', 115),
('Fuente Alemana', '', 116),
('El Rápido', '', 117),
('Juan Maestro', '', 118),
('Starbucks', 'https://starbucks.cl', 119),
('Dunkin''', 'https://dunkindonuts.cl', 120),

-- Turismo & Hotelería
('Latam Airlines', 'https://latamairlines.com', 121),
('Sky Airline', 'https://skyairline.com', 122),
('JetSMART', 'https://jetsmart.com', 123),
('Marriott', 'https://marriott.com', 124),
('Hilton', 'https://hilton.com', 125),
('W Hotels', 'https://marriott.com/w-hotels', 126),
('Casa Piedra', 'https://casapiedra.cl', 127),
('Enjoy', 'https://enjoy.cl', 128),
('Dreams', 'https://mundodreams.com', 129),
('Booking.com', 'https://booking.com', 130),
('Airbnb', 'https://airbnb.com', 131),
('Despegar', 'https://despegar.com', 132),

-- Medios & Entretenimiento
('Mega', 'https://mega.cl', 133),
('Canal 13', 'https://canal13.cl', 134),
('TVN', 'https://tvn.cl', 135),
('CHV', 'https://chilevision.cl', 136),
('La Tercera', 'https://latercera.com', 137),
('El Mercurio', 'https://emol.com', 138),
('Biobío', 'https://biobiochile.cl', 139),
('Radio Concierto', 'https://concierto.cl', 140),
('Spotify', 'https://spotify.com', 141),
('Netflix', 'https://netflix.com', 142),
('Disney+', 'https://disneyplus.com', 143),
('HBO Max', 'https://hbomax.com', 144),

-- Educación
('Duoc UC', 'https://duoc.cl', 145),
('INACAP', 'https://inacap.cl', 146),
('Universidad de Chile', 'https://uchile.cl', 147),
('PUC', 'https://uc.cl', 148),
('Universidad Andrés Bello', 'https://unab.cl', 149),
('Diego Portales', 'https://udp.cl', 150),
('Santo Tomás', 'https://santotomas.cl', 151),
('Udemy', 'https://udemy.com', 152),
('Coursera', 'https://coursera.org', 153),
('Platzi', 'https://platzi.com', 154),

-- Deportes & Fitness
('SportLife', 'https://sportlife.cl', 155),
('Smart Fit', 'https://smartfit.cl', 156),
('Bodytech', 'https://bodytech.cl', 157),
('Decathlon', 'https://decathlon.cl', 158),
('Doite', 'https://doite.cl', 159),
('Lippi', 'https://lippi.cl', 160),
('Colo-Colo', 'https://colocolo.cl', 161),
('Universidad de Chile FC', 'https://udechile.cl', 162),
('Azul Azul', '', 163),
('Blanco y Negro', '', 164),

-- Belleza & Cuidado Personal
('L''Oréal', 'https://loreal.com', 165),
('Maybelline', 'https://maybelline.com', 166),
('Revlon', 'https://revlon.com', 167),
('Dove', 'https://dove.com', 168),
('Pantene', '', 169),
('Head & Shoulders', '', 170),
('Gillette', '', 171),
('Nivea', 'https://nivea.cl', 172),
('Eucerin', 'https://eucerin.cl', 173),
('La Roche-Posay', 'https://laroche-posay.es', 174),

-- Hogar & Decoración
('Sodimac', 'https://sodimac.cl', 175),
('Easy', 'https://easy.cl', 176),
('Ikea', 'https://ikea.com', 177),
('Dimerc', 'https://dimerc.cl', 178),
('Casaideas', 'https://casaideas.cl', 179),
('Corona Casa', 'https://coronacasa.cl', 180),
('Falabella Home', 'https://falabella.com', 181),
('Ripley Home', 'https://ripley.cl', 182),
('Mueblería Nacional', '', 183),
('Basement', 'https://basement.cl', 184),

-- Logística & Transporte
('Chilexpress', 'https://chilexpress.cl', 185),
('Starken', 'https://starken.cl', 186),
('Blue Express', 'https://blueexpress.cl', 187),
('DHL', 'https://dhl.com', 188),
('FedEx', 'https://fedex.com', 189),
('UPS', 'https://ups.com', 190),
('Uber', 'https://uber.com', 191),
('Cabify', 'https://cabify.com', 192),
('inDriver', 'https://indriver.com', 193),
('DiDi', 'https://didiglobal.com', 194),

-- Seguros
('Mapfre', 'https://mapfre.cl', 195),
('Mutual de Seguridad', 'https://mutual.cl', 196),
('BCI Seguros', 'https://bciseguros.cl', 197),
('Chilena Consolidada', 'https://chilenaconsolidada.cl', 198),
('HDI Seguros', 'https://hdi.cl', 199),
('Zurich', 'https://zurich.cl', 200),
('AXA', 'https://axa.cl', 201),
('Bupa Seguros', 'https://bupa.cl', 202),

-- E-commerce & Tech Startups
('MercadoLibre', 'https://mercadolibre.cl', 203),
('Falabella.com', 'https://falabella.com', 204),
('Rappi', 'https://rappi.cl', 205),
('PedidosYa', 'https://pedidosya.cl', 206),
('Uber Eats', 'https://ubereats.com', 207),
('Cornershop', 'https://cornershopapp.com', 208),
('Chek', 'https://chek.cl', 209),
('Fintual', 'https://fintual.cl', 210),
('Buk', 'https://buk.cl', 211),
('NotCo', 'https://notco.com', 212),
('Betterfly', 'https://betterfly.com', 213),
('Platanus', '', 214),
('Kushki', 'https://kushkipagos.com', 215),
('Transbank', 'https://transbank.cl', 216),
('Webpay', 'https://webpay.cl', 217)

on conflict do nothing;
